//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by KingBuilder.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_AMBOTYPE                    129
#define IDB_TABIMAGES                   130
#define IDS_AMBOTYPEBAK                 130
#define IDI_ICONFOLDER                  131
#define IDI_ICONFILE                    132
#define IDD_FINDTEXTDLG                 133
#define IDR_TOOLBAR1                    134
#define IDR_BUILDBAR                    135
#define IDD_SETSYSCOLOR                 136
#define IDD_CREATESELECT                137
#define IDD_CREATEINPUT                 138
#define IDR_EDITBAR                     141
#define IDD_OPTION                      144
#define IDD_DIALOG1                     149
#define IDB_TRACEMARK                   150
#define IDI_ROOT                        153
#define IDI_GROUP                       154
#define IDI_MODULE                      155
#define IDI_LIST                        156
#define IDI_SOURCE                      157
#define IDI_DIRECTORY                   158
#define IDD_SYSTEMSETTING               164
#define IDD_NEWBSP                      166
#define IDD_CPUANDBSPDIR                167
#define IDD_NEWPLATFORM_STEP1           168
#define IDD_NEWPLATFORM_STEP2           169
#define IDD_NEWPLATFORM_STEP3           170
#define IDI_SELECTED                    171
#define IDI_UNSELECTED                  172
#define IDR_MATTERVIEWPOPUP             173
#define IDR_EDITPOPUPMENU               174
#define IDD_PLATFORMSET_PAGE1           175
#define IDD_PLATFORMSET_PAGE2           177
#define IDD_SETENV                      178
#define IDD_AVTIVESOFTWARE              179
#define IDD_PLATFORMSET_PAGE3           180
#define IDD_PLATFORMSET_PAGE4           182
#define IDD_PLATFORMSET_PAGE5           184
#define IDD_PLATFORMSET_PAGE6           186
#define IDB_INSERT                      188
#define IDB_DELETE                      189
#define IDB_UPLINE                      190
#define IDB_DOWNLINE                    191
#define IDD_FINDINFILES                 195
#define IDD_REPLACEDLG                  196
#define IDR_PROJECTPOPUP                197
#define IDD_NEWFOLDER                   198
#define IDD_MODULESELECT                199
#define IDC_MARKALL                     1000
#define IDC_WORKSPACESNAME              1001
#define IDC_FIND_NEXT                   1001
#define IDC_FINDTEXTCOMBO               1002
#define IDC_LOCATION                    1003
#define IDC_FINDFILTER                  1003
#define IDC_REPLACETEXTCOMBO            1003
#define IDC_FOREGROUND                  1004
#define IDC_SOURCELOCATION              1004
#define IDC_PLATFORMROOT                1004
#define IDC_BROWES                      1005
#define IDC_FINDFOLDER                  1005
#define IDC_REPLACE                     1005
#define IDC_UP_DIR                      1006
#define IDC_SOURCEBROWES                1006
#define IDC_COMBO2                      1007
#define IDC_CPUSELECT                   1007
#define IDC_TEXTLIST                    1007
#define IDC_WARNINGLEVELLIST            1007
#define IDC_REPLACEALL                  1007
#define IDC_DOWNDIR                     1008
#define IDC_BACKGROUND                  1008
#define IDC_WORKSPACE                   1009
#define IDC_RESET                       1009
#define IDC_MATCHALLWORD                1010
#define IDC_EFFECT                      1010
#define IDC_MATCHWHOLEWORD              1010
#define IDC_PROJECT                     1011
#define IDC_MATCHCASE                   1012
#define IDC_MATCH_CASE                  1012
#define IDC_COMBO1                      1012
#define IDC_TEXTFILE                    1013
#define IDC_COLORITEMCOMBO              1014
#define IDC_NEWBSPNAME                  1014
#define IDC_SelColor                    1015
#define IDC_Vendor                      1015
#define IDC_DEFAULTCOLOR                1016
#define IDC_VERSION0                    1016
#define IDC_VERSION1                    1017
#define IDC_VERSION2                    1018
#define IDC_VERSION3                    1019
#define IDC_CPUTYPE                     1019
#define IDC_DESCRIPTION                 1020
#define IDC_BSPPLATFORMNAME             1020
#define IDC_PLATFORMNAME                1021
#define IDC_BROWRES                     1023
#define IDC_BSPLIST                     1024
#define IDC_BROWRES2                    1024
#define IDC_FEATURE                     1025
#define IDC_PROJECTTYPE                 1026
#define IDC_LOADFROMSOURCE              1027
#define IDC_BUILDTYPE                   1028
#define IDC_ENVIRONMENT                 1029
#define IDC_NEWENV                      1030
#define IDC_DELENV                      1031
#define IDC_EDIT1                       1031
#define IDC_EDITENV                     1032
#define IDC_EDIT2                       1032
#define IDC_SELECTDIRFOR                1033
#define IDC_CATEGORYLIST                1035
#define IDC_OPTIMIZATIONSLIST           1036
#define IDC_PREPROCESSOR                1037
#define IDC_PROJECTOPTIONS              1038
#define IDC_OUTPUTFILENAME              1039
#define IDC_OUTPUTMAP                   1040
#define IDC_PPP                         1044
#define IDC_FIND                        1045
#define IDC_LOOKINSUBFOLDER             1046
#define IDC_NEWFOLDERTEXT               1047
#define IDC_BROWSE                      1048
#define ID_PROJECT_MRU_FIRST            0x1110
#define ID_PROJECT_MRU_FILE1            0x1110
#define ID_PROJECT_MRU_FILE2            0x1111
#define ID_PROJECT_MRU_FILE3            0x1112
#define ID_PROJECT_MRU_FILE4            0x1113
#define ID_PROJECT_MRU_FILE5            0x1114
#define ID_PROJECT_MRU_FILE6            0x1115
#define ID_PROJECT_MRU_FILE7            0x1116
#define ID_PROJECT_MRU_FILE8            0x1117
#define ID_PROJECT_MRU_FILE9            0x1118
#define ID_PROJECT_MRU_FILE10           0x1119
#define ID_PROJECT_MRU_FILE11           0x111A
#define ID_PROJECT_MRU_FILE12           0x111B
#define ID_PROJECT_MRU_FILE13           0x111C
#define ID_PROJECT_MRU_FILE14           0x111D
#define ID_PROJECT_MRU_FILE15           0x111E
#define ID_PROJECT_MRU_FILE16           0x111F
#define ID_PROJECT_MRU_LAST             0x111F
#define IDI_MATTERVIEW                  15000
#define IDI_CONFIGVIEW                  15001
#define ID_PUZZLER_NAME                 32771
#define IDM_TEST                        32772
#define ID_TEST1                        32773
#define ID_BUILD                        32774
#define ID_TEST2                        32775
#define ID_COMMANDBAR_SEARCH            32776
#define ID_Test3                        32777
#define ID_TEST4                        32778
#define ID_TEST5                        32779
#define ID_EDIT_TOGGLE_BOOKMARK         32780
#define ID_NEW                          32781
#define ID_EDIT_GOTO_NEXT_BOOKMARK      32782
#define ID_EDIT_GOTO_PREV_BOOKMARK      32783
#define ID_EDIT_CLEAR_ALL_BOOKMARKS     32784
#define ID_VIEW_TESTTOOLBAR             32785
#define ID_VIEW_EDITBAR                 32786
#define ID_SETSYSCOLOR                  32787
#define ID_VIEW_WORKSPACE               32788
#define ID_VIEW_OUTPUT                  32789
#define ID_BOOKMARK                     32790
#define ID_NEXTBOOKMARK                 32791
#define ID_PREVBOOKMARK                 32792
#define ID_CLEARBOOKMARK                32793
#define ID_SEARCHINPUT                  32794
#define ID_COMPILE                      32795
#define ID_STOPBUILD                    32796
#define ID_VIEW_BUILDBAR                32797
#define IDM_COMPILE                     32799
#define IDM_BUILD                       32800
#define IDM_STOPBUILD                   32801
#define IDM_PRJSETTING                  32802
#define IDM_OPTION                      32803
#define IDM_REBUILD                     32804
#define IDM_CLEAN                       32805
#define IDM_MAKEIMAGE                   32806
#define IDM_CONSOLE                     32809
#define IDM_COMPILEFEATURE              32811
#define ID_WINDOW_NEXT                  32814
#define ID_BSPWIZARD                    32816
#define ID_NEWWORKSPACE                 32818
#define ID_OPENWORKSPACE                32819
#define ID_CLOSEWORKSPACE               32820
#define IDM_INSERTFILE                  32821
#define IDM_ACTIVESOFTWARE              32822
#define ID_FINDINFILES                  32823
#define IDM_DELETEITEM                  32824
#define IDM_INSERTFOLDER                32825
#define IDM_REFRESHMODULE               32826
#define IDM_MODULESELECT                32827
#define ID_WINDOW_CLOSEALL              32828
#define IDS_CFILEFILTER                 61446
#define IDS_WORKSPACESFILTER            61447
#define IDS_PROJECTFILTER               61448
#define IDS_TEXTFILTER                  61449
#define IDS_OPENWORKSPACE               61450
#define IDS_SOURCEFILTER                61451
#define IDS_OPENSOURCE                  61452
#define IDS_INSERTFILE                  61453
#define IDS_LIBRARY                     61454
#define IDS_LIBRARYFILTER               61455
#define IDS_CHARSET                     61456
#define IDS_SAVE_CHANGE                 61457
#define IDS_INVALID_PATH                61458
#define IDS_NO_FIND_BUILDER_PATH        61459
#define IDS_STOP_BUILDING               61460

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        200
#define _APS_NEXT_COMMAND_VALUE         32829
#define _APS_NEXT_CONTROL_VALUE         1049
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
